// <auto-generated />
using System;
using EdgeCloud.LES.ClassLibrary.Repository.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EdgeCloud.LES.ClassLibrary.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220525174209_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EdgeCloud.LES.ClassLibrary.Core.ApiRequest.Models.ApiRequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestData")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponseData")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ResponseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ServerImportDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ApiRequestLogs");
                });

            modelBuilder.Entity("EdgeCloud.LES.ClassLibrary.Core.Event.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ServerImportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("EdgeCloud.LES.ClassLibrary.Core.Interaction.Models.InteractionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("InteractionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NavigationInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ServerImportDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InteractionLogs");
                });

            modelBuilder.Entity("EdgeCloud.LES.ClassLibrary.Core.Network.Models.NetworkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ActivityDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ServerImportDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NetworkLogs");
                });

            modelBuilder.Entity("EdgeCloud.LES.ClassLibrary.Core.UserAuthentication.Models.UserAuthenticationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ActivityDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MacAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ServerImportDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
